name: reusable deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: the name of the deployable artifact file
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }} # dist-files
      - name: output information
        run: echo "Deploying & uploading ..."